export enum Categories {
    CLOTHING = "CLOTHING",
    TOOLS = "TOOLS",
    SPORTS = "SPORTS",
    ACCESSORIES = "ACCESSORIES",
    FURNITURE = "FURNITURE",
    PETS = "PETS",
    GAMES = "GAMES",
    BOOKS = "BOOKS",
    TECHNOLOGY = "TECHNOLOGY",
}